# Generated by Django 4.2.4 on 2023-08-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KDrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=200)),
                ('name_kor', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='First Episode Release Date')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('broadcast_ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdramadatabase.broadcastchannel')),
            ],
        ),
    ]
